quirks: ignore path_powerbtn

diff --git a/src/chimeraos-addon/bin/sk-quirks b/src/chimeraos-addon/bin/sk-quirks
--- a/src/chimeraos-addon/bin/sk-quirks
+++ b/src/chimeraos-addon/bin/sk-quirks
@@ -158,12 +158,11 @@ function apply_hhd_patch() {
 
 function apply_hhd_claw() {
     local path_base_url="https://gitee.com/honjow/sk-chos-scripts/raw/master/patchs/"
-    local path_powerbtn=("${path_base_url}hhd-clawa8-fix-powerbutton.patch")
+    # local path_powerbtn=("${path_base_url}hhd-clawa8-fix-powerbutton.patch")
     local path_dynamic_grabbing=("${path_base_url}hhd-claw-dynamic-grabbing.patch")
 
     if [[ "$VENDOR" == "Micro-Star International Co., Ltd." ]]; then
-        if try_patches_in_order "$HHD_PATH" path_powerbtn || echo "Claw power button patch failed" >&2 ||
-            try_patches_in_order "$HHD_PATH" path_dynamic_grabbing || echo "Claw dynamic grabbing patch failed" >&2; then
+        if try_patches_in_order "$HHD_PATH" path_dynamic_grabbing || echo "Claw dynamic grabbing patch failed" >&2; then
             echo "claw hhd patches applied"
         else
             echo "All claw hhd patches failed"
